name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  presubmit:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build github.com/downflux/go-boids
      run: go build github.com/downflux/go-boids/...

    - name: Vet github.com/downflux/go-boids
      run: go vet github.com/downflux/go-boids/...

    - name: Test github.com/downflux/go-boids
      run: go test github.com/downflux/go-boids/... -bench . -benchmem
